<a href="https://colab.research.google.com/github/wilberquito/AMLProject/blob/main/AMLProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning Project: Image Classification
## Advanced Machine Learning


> Wilber E. Bermeo Quito 
>
> Judit Quintana Massana
>
> April 2023

## 

In [ ]:
! pip install torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import zipfile
from pathlib import Path

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!ls /content/drive/MyDrive/AML

dataset_CIFAR10.zip  modular.zip


In [ ]:
data_path = Path('/content/drive/MyDrive/AML/dataset_CIFAR10.zip')
with zipfile.ZipFile(data_path,"r") as zip_ref:
    zip_ref.extractall("data")

In [ ]:
import torch
import torchvision.transforms as transforms
import torchvision

# the training transforms
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.GaussianBlur(kernel_size=(5, 9), sigma=(0.1, 5)),
    transforms.RandomRotation(degrees=(30, 70)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.5, 0.5, 0.5],
        std=[0.5, 0.5, 0.5]
    )
])
# the validation transforms
valid_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.5, 0.5, 0.5],
        std=[0.5, 0.5, 0.5]
    )
])

train_dataset = torchvision.datasets.ImageFolder(root='data/train',transform=train_transform)
valid_dataset = torchvision.datasets.ImageFolder(root='data/validation',transform=valid_transform)

In [ ]:
from torch.utils.data import DataLoader
# batch size
BATCH_SIZE = 64

# training data loaders
train_loader = DataLoader(
    train_dataset, batch_size=BATCH_SIZE, shuffle=True
)
# validation data loaders
valid_loader = DataLoader(
    valid_dataset, batch_size=BATCH_SIZE, shuffle=False
)

In [ ]:
for X, y in train_loader:
  print(y)

tensor([3, 2, 2, 3, 7, 8, 6, 1, 4, 3, 7, 7, 4, 4, 8, 2, 1, 0, 8, 0, 2, 2, 1, 5,
        6, 3, 5, 6, 9, 5, 7, 1, 5, 7, 5, 3, 3, 1, 3, 4, 8, 9, 7, 4, 5, 6, 3, 5,
        9, 0, 3, 1, 4, 5, 8, 1, 7, 7, 5, 0, 9, 7, 5, 0])
tensor([6, 0, 0, 2, 2, 9, 0, 7, 4, 5, 9, 2, 5, 0, 7, 4, 5, 6, 3, 8, 2, 0, 3, 5,
        9, 0, 7, 2, 4, 8, 5, 6, 9, 5, 2, 9, 8, 4, 0, 1, 7, 5, 2, 4, 5, 2, 4, 8,
        2, 2, 2, 3, 7, 5, 4, 1, 2, 5, 6, 5, 3, 0, 1, 4])
tensor([2, 0, 6, 1, 5, 3, 0, 5, 5, 7, 3, 7, 2, 2, 2, 4, 8, 5, 1, 3, 2, 6, 3, 9,
        8, 7, 8, 3, 4, 9, 5, 8, 6, 0, 2, 2, 4, 6, 4, 0, 3, 9, 4, 2, 8, 6, 9, 3,
        1, 1, 7, 4, 6, 6, 0, 7, 9, 0, 4, 8, 2, 7, 9, 1])
tensor([0, 4, 0, 5, 0, 6, 7, 2, 8, 2, 9, 8, 1, 0, 0, 1, 1, 0, 1, 8, 9, 3, 1, 4,
        6, 2, 7, 3, 3, 4, 5, 3, 2, 5, 0, 6, 6, 4, 9, 1, 3, 3, 4, 3, 0, 9, 4, 0,
        9, 7, 8, 6, 0, 7, 2, 0, 9, 4, 7, 9, 5, 1, 8, 6])
tensor([2, 7, 1, 8, 0, 4, 3, 9, 8, 0, 6, 8, 6, 3, 7, 2, 9, 5, 2, 4, 4, 0, 5, 6,
        7, 0, 3, 2, 6, 0, 8, 5, 9, 7, 6, 7, 0, 1, 5,

In [ ]:
from modular.modular import models